---
- name: pacman -S samba
  community.general.pacman: name=samba state=present
  become: true
  when: ansible_distribution == "Archlinux"

- name: dnf install samba
  ansible.builtin.dnf: name=samba state=present
  become: true
  when: ansible_distribution == "Fedora"

- name: Create /etc/samba/smb.conf
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    validate: testparm -s %s
  become: true

- name: Create samba share directories
  ansible.builtin.file:
    path: "/srv/smb/{{ item.name }}"
    state: directory
  become: true
  loop: "{{ smb_share }}"

- name: Add bind mount to /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: "^{{ item.path }}\\s+/srv/smb/{{item.name }}"
    line: "{{ item.path }}  /srv/smb/{{item.name }}  none  bind  0 0"
    state: present
  become: true
  loop: "{{ smb_share }}"

#- name: Add custom Samba rule to UFW
#  ansible.builtin.blockinfile:
#    path: /etc/ufw/applications.d/ufw-custom
#    block: | 
#      [Samba-custom]
#      title=SMB/CIFS server
#      description=SMB/CIFS server
#      ports=445/tcp
#    create: true
#    marker: "; SMB/CIFS {mark} ANSIBLE MANAGED BLOCK"
#
#- name: Configure firewall for CIFS
#  community.general.ufw:
#    rule: allow
#    direction: in
#    name: Samba-custom
#    from: "{{ item }}"
#    comment: "Allow SMB/CIFS from {{ item }}"
#  loop: "{{ CIFS_allow_ip }}"

- name: Create samba user
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: '!'
    password_lock: true
    create_home: false
    uid: "{{ item.uid }}"
    shell: "/usr/bin/nologin"
  become: true
  when:
    - item.name != ansible_user_id
    - item.name != "root"
  loop: "{{ smb_users }}"

- name: Add samba user
  shell: (echo {{ item.passwd }}; echo {{ item.passwd }}) | smbpasswd -s -a {{ item.name }}
  become: true
  register: samba_user
  changed_when: "'Added user' in samba_user.stdout"
  loop: "{{ smb_users }}"

- name: Modify samba firewalld service file samba.xml
  ansible.builtin.copy:
    content: |
      <?xml version="1.0" encoding="utf-8"?>
      <service>
        <short>Samba</short>
        <description>Modified samba server only accept 445/tcp port.</description>
        <port protocol="tcp" port="445"/>
      </service>
    dest: /etc/firewalld/services/samba.xml
    owner: root
    group: root
    mode: '0644'
  become: true
  register: samba_firewalld_file

- name: Reload firewalld when samba.xml changed
  ansible.builtin.command: firewall-cmd --reload
  become: true
  when: samba_firewalld_file.changed

- name: Set firewall rules for samba
  ansible.posix.firewalld:
    rich_rule: rule family="ipv4" source address="{{ item }}" service name="samba" accept
    #zone: "{{ firewalld_default_zone }}"
    permanent: true
    immediate: true
    state: enabled
  become: true
  loop: "{{ samba_accept_source_ipv4 }}"
  when: samba_accept_source_ipv4 is defined

- name: systemctl enable smb.service
  ansible.builtin.systemd: name=smb enabled=true
  become: true

- name: Set SELinux file context to shared directories
  community.general.sefcontext:
    target: "{{ item.path }}(/.*)?"
    setype: samba_share_t
    state: present
  become: true
  when: ansible_selinux.status == "enabled"
  loop: "{{ smb_share }}"
  register: samba_share_sefcontext

- name: Apply SELinux file context to shared directories
  ansible.builtin.command: "restorecon -R {{ item.path }}"
  become: true
  when:
    - ansible_selinux.status == "enabled"
    - samba_share_sefcontext.changed
  loop: "{{ smb_share }}"

